version: 2.1
executors:
  ci-executor:
    docker:
      - image: REPLACE-ME-WITH-DOCKER-IMAGE
      - image: githubtraining/ci-custom:latest
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
